spring:
  application:
    name: telco-eureka-respaldo
  datasource:
    url: jdbc:h2:mem:calldb
    username: root
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8075

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost